version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4567-4584:4567-4584
      - 8080:8080
    networks:
      - sam-localstack
    environment:
      SERVICES: ses,cloudwatch
      DEFAULT_REGION: eu-central-1
networks:
  sam-localstack:
    external: true